# Generated by Django 3.2.8 on 2021-10-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('wo', 'Arbeit'), ('br', 'Pause'), ('za', 'Zeitausgleich')], default='wo', max_length=2)),
                ('time_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('stop_time', models.TimeField(blank=True)),
            ],
        ),
    ]
