# Generated by Django 3.2.8 on 2021-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='type',
            field=models.CharField(choices=[('wo', 'Arbeit'), ('br', 'Pause')], default='wo', max_length=2),
        ),
    ]
