# Generated by Django 3.2.8 on 2021-10-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0002_auto_20211020_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='stop_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='time_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
