# Generated by Django 3.2.8 on 2021-10-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0003_auto_20211021_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='time_total',
            field=models.CharField(default='', max_length=16),
        ),
    ]
