# Generated by Django 3.2.8 on 2021-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0004_alter_timer_time_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='type',
            field=models.CharField(choices=[('work', 'Arbeit'), ('break', 'Pause')], default='work', max_length=10),
        ),
    ]
