# Generated by Django 3.2.8 on 2021-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0006_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'verbose_name': 'Timer', 'verbose_name_plural': 'Timer'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
