# Generated by Django 3.2.8 on 2021-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0007_auto_20211022_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='work_hours_per_week',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=4),
        ),
    ]
