# Generated by Django 3.2.8 on 2021-10-24 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0008_usersettings_work_hours_per_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='timer',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
