# Generated by Django 3.2.8 on 2021-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('comp', 'Zeitausgleich'), ('sick', 'Krankenstand'), ('vacation', 'Urlaub')], default='vacation', max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'Akzeptiert'), ('pending', 'Austehen'), ('denied', 'Abgelehnt')], default='pending', max_length=10)),
                ('reviewed_by', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Application',
            },
        ),
    ]
