# Generated by Django 3.2.8 on 2021-10-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211026_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed_by',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Akzeptiert'), ('pending', 'Austehend'), ('denied', 'Abgelehnt')], default='pending', max_length=10),
        ),
    ]
