# Generated by Django 3.2.8 on 2021-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211026_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed_by',
            field=models.IntegerField(default=0),
        ),
    ]
